receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # Metrics → Prometheus (collector exposes /metrics)
  prometheus:
    endpoint: 0.0.0.0:8889

  # Logs → Loki via OTLP/HTTP
  otlphttp/loki:
    endpoint: http://loki:3100/otlp

  # Traces → Tempo via OTLP/HTTP
  otlphttp/tempo:
    endpoint: http://tempo:4318

  # Optional local debugging
  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug, otlphttp/loki]

    metrics:
      receivers: [otlp]
      exporters: [prometheus]

    traces:
      receivers: [otlp]
      exporters: [otlphttp/tempo]
