name: .NET Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'   # or '9.0.x' if you're on .NET 9
          cache: true               # NuGet cache

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Test (with coverage)
        run: >
          dotnet test
          --configuration Release
          --no-build
          --logger "trx;LogFileName=test_results.trx"
          --collect "XPlat Code Coverage"
          --results-directory TestResults

      - name: Upload test results
        if: always()   # upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/*.trx
            **/TestResults/*/coverage.cobertura.xml
          if-no-files-found: warn
